# Generated by Django 5.0.2 on 2024-02-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="reset_password_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="reset_password_token_expiration",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
